name: Python CI with Docker and Docker Hub

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    environment: staging  # Utilise l'environnement "staging"

    steps:
      # Étape 1 : Récupère le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configure Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Étape 4 : Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/online-retail-pipeline:latest .

      # Étape 5 : Exécuter les tests dans un conteneur Docker
      - name: Run tests in Docker container
        run: |
          docker run ${{ secrets.DOCKER_HUB_USERNAME }}/online-retail-pipeline:latest python -m pytest tests/

      # Étape 6 : Pousser l'image Docker (uniquement sur la branche main)
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/online-retail-pipeline:latest