name: Python CI

# Déclenche le workflow à chaque push ou pull request sur les branches main ou master
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

# Définit les jobs à exécuter
jobs:
  test:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu

    steps:
      # Étape 1 : Récupère le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configure Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Version de Python à utiliser

      # Étape 3 : Installe les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Exécute les tests
      - name: Run tests
        run: |
          python -m pytest tests/