name: Python CI with Docker and Docker Hub

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/online-retail-pipeline:latest .

      - name: Run tests in Docker container
        run: |
          docker run ${{ secrets.DOCKER_HUB_USERNAME }}/online-retail-pipeline:latest python -m pytest tests/

      - name: Push Docker image
        if: github.ref == 'refs/heads/master'  # Condition modifiée pour master
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/online-retail-pipeline:latest